# azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionId: 'd5b1b63d-6ad0-4043-bf2f-58ae53af527e'
  webAppName: 'GoshJavaWebapp'
  javaVersion: '11'  # Java version used in the build and runtime
  artifactName: 'webapp'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: MavenAuthenticate@0
  inputs:
    mavenServiceConnections: '$(azureServiceConnectionId)'

- script: mvn clean package
  displayName: 'Build Java Web App'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    appType: webApp
    azureSubscription: '$(azureServiceConnectionId)'
    appName: '$(webAppName)'
    package: '$(System.DefaultWorkingDirectory)/target/$(artifactName).war'
